name: Deploy WordPress to Hosting

on:
    push:
        branches:
            - main # Triển khai khi có thay đổi trên nhánh main

jobs:
    deploy:
        name: Deploy Website
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Upload files via FTP
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                  server: ${{ secrets.FTP_SERVER }} # Thay đổi từ 'ftp-server' thành 'server'
                  username: ${{ secrets.FTP_USERNAME }} # Thay đổi từ 'ftp-username' thành 'username'
                  password: ${{ secrets.FTP_PASSWORD }} # Thay đổi từ 'ftp-password' thành 'password'
                  port: 21 # Cập nhật cổng nếu cần
                  local-dir: "./" # Thư mục mã nguồn
                  server-dir: ${{ secrets.FTP_PATH }} # Thư mục trên server
                  exclude: |
                      .git*
                      .github/
                      node_modules/
                      **/*.md
